### ISSUE TITLE
How to effectivily pass multiple items for checkout

### ISSUE THREAD

**Issue by karthika89** [paypal/PayPal-Android-SDK#184]
I am using the following code to place a test order from json.

```
                    PayPalItem[] items =new PayPalItem[orders.length()];
                    for(int i=0;i<orders.length();i++) {
                        items[i]=new PayPalItem(orders.getJSONObject(i).getString("name"), orders.getJSONObject(i).getInt("qty"),
                                new BigDecimal(orders.getJSONObject(i).getDouble("name")), "USD",
                                orders.getJSONObject(i).getString("sku"));
                    }

                        BigDecimal subtotal =new BigDecimal(productRes.getDouble("subtotal_exc_tax"));
                        BigDecimal shipping = new BigDecimal(("7.21"));
                        BigDecimal tax = new BigDecimal(productRes.getDouble("tax"));
                        PayPalPaymentDetails paymentDetails = new PayPalPaymentDetails(shipping, subtotal, tax);
                        BigDecimal amount = new BigDecimal(productRes.getDouble("subtotal_incl_tax"));
                         payment = new PayPalPayment(amount, "USD", "sample item", PayPalPayment.PAYMENT_INTENT_SALE);
                        payment.items(items).paymentDetails(paymentDetails);

                        //--- set other optional fields like invoice_number, custom field, and soft_descriptor
                        payment.custom("Payment from android app");
```
but it's not working.

**Comment by notsoux** [comment]
Something similar happened to me: I need to buy one thing per purchase and I cannot get back the SKU contained in json "Items" that PayPal should give back as response.

**Comment by jaypatel512** [comment]
Hey @karthika89 ! Just to confirm, when you are passing the items to the paypal request, and complete the flow, on response, you are not receiving any item_list back, right ? I am trying to reproduce this issue, and want to confirm that.

**Comment by jaypatel512** [comment]
Hey @karthika89 ! 

Here are my few pointers to debug this issue:

1. I ran the [SampleApp](https://github.com/paypal/PayPal-Android-SDK/tree/master/SampleApp) that comes packaged with the Android SDK. 
2. I saw that there are two methods provided in Sample for Payments: [`getThingToBuy`](https://github.com/paypal/PayPal-Android-SDK/blob/master/SampleApp/src/com/paypal/example/paypalandroidsdkexample/SampleActivity.java#L101) and [`getStuffToBuy`](https://github.com/paypal/PayPal-Android-SDK/blob/master/SampleApp/src/com/paypal/example/paypalandroidsdkexample/SampleActivity.java#L109). 
3. Change [this line](https://github.com/paypal/PayPal-Android-SDK/blob/master/SampleApp/src/com/paypal/example/paypalandroidsdkexample/SampleActivity.java#L85) to use `getStuffToBuy`  instead of `getThingToBuy`, as shown below:
    ```java
    PayPalPayment thingToBuy = getStuffToBuy(PayPalPayment.PAYMENT_INTENT_SALE);
    ```

4. Run and confirm if you are seeing the `item_list` in the response, in logCat. I am.

Let me know if this helps you resolve the issue you are trying to solve.

**Comment by jaypatel512** [comment]
Any updates @karthika89 ? or @notsoux ?

I will close this issue, as I was able to confirm that the item_list is retrievable in the sampleApp provided in sandbox environment. Please re-open this, if you are seeing otherwise after the above fix.

**Comment by kotdroidZero** [comment]
[Please give any solution for this](https://github.com/paypal/PayPal-Android-SDK/issues/484)
