### ISSUE TITLE
Unknown server error while doing payment in sandbox mode

### ISSUE THREAD

**Issue by sachin62** [paypal/PayPal-Android-SDK#207]
not able to do payment in sandbox mode but able to do payment in no network mode.Always give unknown_error from server.my debug id is:-63cb8ee9540e5.

**Comment by ppmtscory** [comment]
@sachin62 you are using an India account to both send and receive funds.  Domestic payments are not allowed for India so, in order to correct this issue, you'll need to use a non-India buyer account to test with.  You can create sandbox accounts for different countries within the developer portal.  As a side note, I've filed an issue internally to have the error message reflect what's actually happening.

**Comment by sachin62** [comment]
So will it work fine in production mode.Please reply as soon as posible,as i am planning to go live.

**Comment by ppmtscory** [comment]
This rule is the same for Production.  Domestic payments (India -> India) are not allowed with PayPal - only International payments.
