### ISSUE TITLE
How to prevent client from submitting their own invoice_number?

### ISSUE THREAD

**Issue by xkjyeah** [paypal/PayPal-Android-SDK#230]
I am concerned about the fact that payment (amounts, items, invoice numbers) are created entirely on the client side.

If clients are free to set their own invoice numbers, and if invoice numbers are predictable (e.g. auto-increment integer), could malicious clients not create a payment with a future invoice number, and block certain those future transactions?

Moreover, if some clients make a payment without submitting their payment resource id for verification (e.g. the app crashes), wouldn't it be impossible for the server to verify the payment, except by polling the PayPal REST API?

**Comment by ppmtscory** [comment]
@xkjyeah if I misunderstand anything, please do let me know.  For your invoice question, the individual merchant wouldn't set the invoice manually - that'd be set in the code in the App.  I suppose if something was hacked, an invoice number used, and the merchant has 'block duplicate invoices' turned on, then there would be the case you're looking at.  However, I'm failing to see where that'd be a huge issue or where the motivation would be for a malicious client to use an invoice number that the merchant would happen to use in the future.

For verification, you could also integrate [Webhooks](https://developer.paypal.com/docs/integration/direct/rest-webhooks-overview/#event-type-support) to get the PayID.  Otherwise, yes, if the PayID isn't returned to the server side for some reason, you'd need to do a call to get a list of recent transactions and then verify at that point.

**Comment by xkjyeah** [comment]
I think you've got the point. It is basically a DoS attack. While I don't
anticipate being attacked any time soon, how is it acceptable that clients
are allowed to generate invoice ids on their own? Doesn't this make
disputes hard to resolve? It also introduces the possibility of conflicts
between the accounting system and PayPal.

From the way it looks, it would make reconciliation with the accounts flaky
for literally anyone who publishes their client ID anywhere. Put another
way, would PayPal let me generate transaction IDs?

A Cordova plugin exists for this SDK, so "hacking" the app is easy.

As far as I understand, WebHooks cannot be used with direct credit card
transactions, which makes it almost useless for my application (so far our
customers pay mostly by credit card).

Sorry for the long rant. In short, the whole system seems to be put
together in a very flaky way, lacking the back-and-forth verifications that
accompany browser payments.

**Comment by xkjyeah** [comment]
Your mobile payments system is broken. As a broker, PayPal ought to ensure
that both the server and client have authorised a payment. How this is done
correctly with your web interface is that PayPal gives the customer a token
which the server submits to PayPal as proof of payment authorization.

In mobile payments, the client and PayPal complete the transaction without
verification from the server. I don't know how to describe this other than
as "fundamentally broken".

Just because it "hasn't been a major issue" doesn't change this fact. #170
---
I'll give a bit of background: I need the invoice numbers because your
system is broken. Some of our clients were being charged multiple times by
PayPal due to an obscure Android bug. This could have been avoided it its
entirety had our servers verified each transaction before it is executed.
To get around this bug, we need a system of unique invoice numbers. And it
so happens that even your invoice number system is broken. Do I really have
to include a message authentication code with every invoice number? Or poll
PayPal for transactions that aren't supported by WebHook? I really don't
know what to say.

**Comment by ppmtscory** [comment]
Having the ability to provide your own Invoice ID is a **HUGE** demand by merchants and partners for reconciliation purposes.  They like to have the invoice ID so that they can match up the payment with their backend systems.  With that being said, if you run into a duplicate invoice error (for whatever reason), you would just update to a different invoice number and re-run the payment.  

I'd like to understand your comment about the difference between web and mobile PayPal payments better.  Are you referring to the EC token from the web or what token are you referring to?  The reason i ask is that the mSDK is simply a wrapper for the REST API which uses those same EC tokens *internally* when processing the payment.  The same process is used via web or mobile, however mobile has the extra 'verify payment' step to confirm that the mobile response came from PayPal.

**Comment by xkjyeah** [comment]
That is exactly why the Android client should not be able to set the
invoice number without verification from the App server.

Payments on a web browser work as follows (if I am not mistaken):
1. Server app creates a payment object, sends approving URL to client
2. Client access approving URL, authorised the payment and sends the
authorisation token to server.
3. Server executes payment using the authorisation token.

At each step, if the client disagrees on the price, or the server disagrees
on the invoice number or price, the process will not complete.

What makes me surprised about the Android SDK is that 1) the app server is
not responsible for creating the payment, but the Android client. 2) the
client completes the transaction without access to the "client secret"
which is stored on the server. (I am not aware of how this is possible with
the REST API).

If as you say the Android client uses the REST API, where does it get the
client secret from, with which it calls the SDK?

**Comment by ppmtscory** [comment]
@xkjyeah yes, the mSDK uses the same flow as online, however it does the execute call internally to limit the need for further interaction from the customer.  Then the verify step is there to ensure that the transaction response wasn't spoofed and actually came from PayPal.  Also, as for the client secret, again PayPal uses internal calls to ensure everything is processed correctly.

For invoice number, while I understand your concerns, the bottom line is that they are meant to be customize-able to allow for flexibility in the integration.  If you need extra validation of invoice number with your backend system prior to payment, then that would be something that you'd have to integrate into your application.  Perhaps you could run the transactions as authorizations and then double check the invoice number when calling to verify the payment.  If everything is good to go, then capture the funds, otherwise void the authorization and let the consumer know that there was an issue with their payment.

**Comment by xkjyeah** [comment]
What do you mean by "execute the call internally"? You mean that the mobile
SDK is specially privileged to execute transactions without verification
from the app server? Otherwise, how can this be done without a client
secret? Doesn't this mean that anyone can pay me money... And if they
choose to withhold the transaction response, I will not be able to see
where it comes from? I mean, that's great for my wallet, but rather bad for
accounting isn't it?

As for invoice numbers, I am not asking for PayPal to generate my invoice
numbers. Because the payment is executed entirely on the client side with
no verification by the app server, a hacked client app (or any app with my
client ID) could generate any payment with any invoice number. I just want
some degree of control before this unique number is allocated to a
particular (possible unsolicited) payment.

Does PayPal's mobile payments flow support that?

**Comment by ppmtscory** [comment]
@xkjyeah the buyer gives authorization of the payment by going through the payment flow and clicking the pay button.  Once that's done, the SDK processes the payment and knows where to send the money based on the client ID that's used.  Yes, anybody can send you money, but the 'verify payment' step is where you will validate that it's a legitimate transaction response from PayPal.  Anybody who hacks your app is *not* going to send you money, they're just going to send your server a made up transaction response in hopes that you don't verify it and just treat it as a processed payment. 

As for your control of Invoice numbers, my last suggestion of running transactions of auth/capture would be a way to have some extra control.

**Comment by xkjyeah** [comment]
Really, admit it: it would be a lot simpler to have stuck to the 3-party
consensus model that PayPal has used with the EC tokens. What was wrong
with that? PayPal's servers can't handle 3 requests instead of 2?

You'd get rid of this bug and bug #170, and gain a system that's robust to
failure (unless my belief that PayPal's servers are more reliable than
consumer devices and cheap web hosts is misplaced). At this stage, I am
just ranting without any expectation of resolution, or admission on your
part of a fundamental flaw in the design. Go ahead and close the bug.

**Comment by ppmtscory** [comment]
@xkjyeah there could be arguments made for both sides, for sure.  We appreciate the feedback!
