### ISSUE TITLE
Paypal sdk 2.13.3 not working on eclipse

### ISSUE THREAD

**Issue by HieuKQ** [paypal/PayPal-Android-SDK#266]
I download new version paypal sdk 2.13.3 for my app android but I don't know use it because it is file .aar and I had convert file .aar to file .jar but it not working so how do I can use it?Please, can you help me?

**Comment by jaypatel512** [comment]
Since the introduction of aar package in Android, we have adopted it to enable better packaging for Android Studio. For applications still using eclipse as developement IDE, there are many plugins, and workarounds to get aar package to work with it.

Here are few of the links providing helpful hits around it: 
- http://stackoverflow.com/questions/23777423/aar-in-eclipse-ant-project
- https://commonsware.com/blog/2014/07/03/consuming-aars-eclipse.html

**Comment by HieuKQ** [comment]
But when I use new version with eclipse I can't see button pay with credit card and if I build sample with android studio so I can see and I can pay with credit card. please, Can you help me use pay with credit card on elipse?
