### ISSUE TITLE
Instrument declined

### ISSUE THREAD

**Issue by zizutg** [paypal/PayPal-Android-SDK#282]
While trying to fetch from multiple sources 2.14. 0 

![kakaotalk_20160401_135339652](https://cloud.githubusercontent.com/assets/14349892/14199749/e9b89cec-f821-11e5-92af-00f3999ccb48.jpg)

![kakaotalk_20160401_135854064](https://cloud.githubusercontent.com/assets/14349892/14199741/e13ce4ba-f821-11e5-8718-3e96ceb90622.jpg)

request failed with server response:{"name":"INSTRUMENT_DECLINED","debug_id":"d52cc9d1a5e47","message":"The instrument presented  was either declined by the processor or bank, or it can't be used for this payment.

**Comment by ppmtscory** [comment]
@zizutg your funding source is being denied for every attempt.  We're getting back the denial directly from your card issuer so you'll need to contact them to see what the problem is exactly.  For payment denials such as this, since they are not a direct issue with the SDK, it's better off just to contact our customer support folks by clicking the contact us link at the bottom of any PayPal page.  They'll be able to look into your account and see more things than we can.

**Comment by zizutg** [comment]
Why wont the sdk allow me to choose my preferred method, instead of summing up the balance

**Comment by ppmtscory** [comment]
If you carry a balance in your PayPal account, PayPal will always use that first.  The funding you are choosing in the flow is what funding you'd want to use for the remainder of the amount.
