### ISSUE TITLE
PAYMENT_CREATION_ERROR

### ISSUE THREAD

**Issue by tillram** [paypal/PayPal-Android-SDK#285]
in ENVIRONMENT_PRODUCTION

This error occurs

E/paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"d8fdcbe091e50","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
E/paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by ppmtscory** [comment]
@tillram please refer to your [SO Post](http://stackoverflow.com/questions/36499928/paypal-payment-creation-error/36509011#36509011) for my answer that I provided the other day.  This doesn't have anything to do with the SDK or your code, but rather the funding source that's being used.  You'll need to reach out to our Customer Support folks to take a further look at that.

**Comment by tillram** [comment]
I do not speak English well , sorry.

Hi. this answer does not resolve the problem, ios application will work correctly using the same account (customer ID )

if we use the same data for android it does not work.

It's very strange. I have spoken with paypal technical support and say that the problem is not theirs .

**Comment by ppmtscory** [comment]
Unfortunately there isn't anything that the engineering team here can do.  This isn't a problem with the SDK or the code at all.  I've notated your buyer account with the information I gathered from looking up the debug ID you provided.  This will give our Customer Support team more information on where the issue lies so they can assist you further.
