### ISSUE TITLE
request failure with http statusCode:422,exception:Unprocessable Entity

### ISSUE THREAD

**Issue by pavan34** [paypal/PayPal-Android-SDK#377]
### Required Information

- Mode (Mock/Sandbox/Live): LIVE
- PayPal Android SDK Version: 2.15.1
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...): All devices
- PayPal-Debug-ID(s) (from any logs): fd96241cc7e1d

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.

12-28 12:38:17.445 4865-6474/com.erbauen.voyageup W/paypal.sdk: fd SN:11 PayPal Debug-ID: fd96241cc7e1d [live, 2.15.1;release]
12-28 12:38:17.445 4865-6474/com.erbauen.voyageup E/paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
12-28 12:38:17.445 4865-6474/com.erbauen.voyageup E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"fd96241cc7e1d","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
12-28 12:38:17.449 4865-4865/com.erbauen.voyageup E/paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by ppmtscory** [comment]
@pavan34 both sender and receiver accounts are registered in India.  Domestic payments are currently not allowed in India - only international payments.  For future, since this error is not specific to an issue with the SDK, please file a ticket with our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team to look into the error.
