### ISSUE TITLE
Question - How to customize the payment activities

### ISSUE THREAD

**Issue by rranjithkumar100** [paypal/PayPal-Android-SDK#438]
In **PaymentActivity** I want to change the theme & also I want to add some customisation. 

**How to customise PaymentActivity?**

**Comment by bluk** [comment]
@rranjithkumar100 The experience is not customizable for this SDK due to various requirements. If you can use [Express Checkout with Braintree SDKs](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/client-side/android/v2/) for one time checkouts or [Braintree directly](https://www.braintreepayments.com/) for one time checkout and more advanced flows, it provides a simpler experience IMO which might be more suitable for your app.
