### ISSUE TITLE
App freezes when calling startService on PayPalConfiguration

### ISSUE THREAD

**Issue by kelvin95** [paypal/PayPal-Android-SDK#83]
When we call startService on a PayPalConfiguration object, our app freezes and gives the message "Application not responding". We started seeing this after moving to SDK Version 2.2.1 and we've been able to consistently reproduce the issue on BLU phone running Android 2.4.1. 

Can you please look into this issue for us? Thanks!

**Comment by HamzehSoboh** [comment]
Using the latest release, having the same problem on the very first start of the service, testing on Sony Z3 and getting the following log:

**_I/Choreographer: Skipped 30 frames!  The application may be doing too much work on its main thread._**

Please reopen this issue until it's really resolved.

Thanks.

**Comment by pp-randy** [comment]
@HamzehSoboh I apologize that you are encountering a problem with the SDK.  This issue was resolved three years ago, and most likely something else is causing this to occur than what has caused this particular problem. Can you consider creating a new issue and provide the requested details in the new issue template that will be populated in the text area?
